name: xlstm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cuda=12.4
  - cuda-nvcc=12.4
  - gxx_linux-64=13.2.0
  - python=3.11
  - pip
  - pytorch=2.4.0
  - pytorch-cuda=12.4
  - cmake
  - ninja
  - cuda-toolkit=12.4
  - cuda-cccl=12.4
  - pip:
      - pre-commit
      - ipykernel
      - dacite
      - omegaconf
      - torchmetrics
      - tqdm
      - pytest
      - pytest-xdist
      - numpy<2.0
