[build-system]
requires = [
  "scikit-build-core>=0.11",
  "pybind11>=3.0",
  "torch>=2.0",
]
build-backend = "scikit_build_core.build"

[project]
name = "xlstm"
version = "2.0.6"
authors = [
  { name="Maximilian Beck", email="beck@ml.jku.at" },
  { name="Korbinian Poeppel", email="poeppel@ml.jku.at" },
  { name="Andreas Auer", email="auer@ml.jku.at" },
]
description = "A novel LSTM variant with promising performance compared to Transformers or State Space Models."
readme = "README.md"
license = {file="LICENSE"}
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
keywords = ["LSTM", "Transformer", "Machine Learning", "Deep Learning", "State Space Models"]
dependencies = [
    "torch>=2.0",
    "PyYAML",
    "safetensors",
    "packaging",
    "ninja",
    "mlstm_kernels; python_version >= '3.11'",
]

[tool.uv]
cache-keys = [
    {file = "pyproject.toml"},
    {file = "CMakeLists.txt"},
    {file = "blocks/slstm/src/cuda/*.c"},
    {file = "blocks/slstm/src/cuda/*.cc"},
    {file = "blocks/slstm/src/cuda/*.h"},
    {file = "blocks/slstm/src/cuda/*.cu"},
    {file = "blocks/slstm/src/cuda/*.cuh"},
    {file = "blocks/slstm/src/util/*.c"},
    {file = "blocks/slstm/src/util/*.cc"},
    {file = "blocks/slstm/src/util/*.h"},
    {file = "blocks/slstm/src/util/*.cu"},
    {file = "blocks/slstm/src/util/*.cuh"},
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
  # { index = "pytorch-cu130", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]


[tool.scikit-build]
minimum-version = "build-system.requires"

[tool.pytest.ini_options]
pythonpath = ["."]
log_cli = true
log_cli_level = "INFO"
log_format = "%(asctime)s %(levelname)s %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"


[project.urls]
Repository = "https://github.com/NX-AI/xlstm"
Issues = "https://github.com/NX-AI/xlstm/issues"
